### ISSUE TITLE
Add Flir S60 sdk

### ISSUE THREAD

**Issue by xdeop** [george-haddad/thermic#3]
Hi,
Could you upload the FLIR S60 sdk (.aar) in the github project as it is not downloadable from its site?

Thanks.

**Comment by george-haddad** [comment]
Committing the SDK into the repo is usually not something I do or recommend others doing. Anyone can get the SDK, you just need to register on the flir website for free and then download it. https://developer.flir.com/mobile/ or  https://developer.flir.com/mobile/flirmobilesdk/

**Comment by xdeop** [comment]
Hi, I know, but I've already registered and downloaded the sdk from your link and it downloads a different one than the one you're using. There's no flironesdk.aar, there's an androidsdk.aar and a thermalsdk.aar. And it says nothing about the support of this new sdk and the Cat S60...

I've asked for your flireonesdk library as per your project here it is ensured to work with the Cat S60.

Thanks.

**Comment by george-haddad** [comment]
Oh ok, I haven't touched this project for a while, so if Flir changed their SDKs then it means this project needs to be updated to reflect the changes. Makes sense in this way.

**Comment by xdeop** [comment]
Hi,
Are you planning to update the project then?

Thanks.

**Comment by george-haddad** [comment]
Yes, when I have some free time, perhaps the weekend.

**Comment by xdeop** [comment]
Ok. I'll keep an eye on it!

**Comment by xdeop** [comment]
In the meantime, could you provide the flironesdk.aar file to test your code?
Thanks.

**Comment by NaujOinotna** [comment]
Hi, could you provide the flironesdk.aar file to test your code please?
Thanks.

**Comment by bukowa** [comment]
Hey, any chance to get this compiled these days?
